eval.batch_size: 1
eval.cutoff_len: 1024
eval.dataset:
- test1
eval.dataset_dir: data
eval.max_new_tokens: 512
eval.max_samples: '100000'
eval.output_dir: eval_2025-06-12-19-10-48
eval.predict: true
eval.temperature: 0.95
eval.top_p: 0.7
top.booster: auto
top.checkpoint_path: []
top.finetuning_type: lora
top.model_name: Qwen2.5-7B-Instruct
top.quantization_bit: none
top.quantization_method: bnb
top.rope_scaling: none
top.template: qwen
