adapter_name_or_path: saves/Qwen3-8B-Base/lora/train_2025-06-12-21-46-59
cutoff_len: 1024
dataset_dir: data
do_predict: true
eval_dataset: test1
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: /root/autodl-tmp/Master_lzz/LLaMA-Factory/models/Qwen/Qwen3-8B-Base/Qwen/Qwen3-8B-Base
output_dir: saves/Qwen3-8B-Base/lora/eval_2025-06-12-23-07-52
per_device_eval_batch_size: 4
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
stage: sft
temperature: 0.95
template: default
top_p: 0.7
trust_remote_code: true
